"""core/renderer のテスト."""

from datetime import UTC, datetime

from ai_agent_monitoring.core.models import (
    LogEntry,
    LogExcerpt,
    PanelSnapshot,
    RCAReport,
    RootCause,
    TriggerType,
)
from ai_agent_monitoring.core.renderer import render_rca_markdown


class TestRenderRCAMarkdown:
    def test_render_with_alert(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
            root_causes=[
                RootCause(
                    description="メモリリーク",
                    confidence=0.9,
                    evidence=["MemAvailable が 100MB以下"],
                ),
            ],
            metrics_summary="CPU使用率が95%超過",
            logs_summary="OOMエラーが発生",
            recommendations=["メモリ上限を引き上げる"],
        )
        md = render_rca_markdown(report)

        assert "# RCA レポート" in md
        assert "HighCPUUsage" in md
        assert "critical" in md
        assert "メモリリーク" in md
        assert "90%" in md
        assert "█████████░" in md  # confidence bar
        assert "メモリ上限を引き上げる" in md

    def test_render_with_user_query(self, sample_user_query):
        report = RCAReport(
            trigger_type=TriggerType.USER_QUERY,
            user_query=sample_user_query,
            root_causes=[],
        )
        md = render_rca_markdown(report)

        assert "ユーザ問い合わせ" in md
        assert "昨日の16時ごろ" in md
        assert "根本原因を特定できませんでした" in md

    def test_render_with_panel_snapshots(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
            panel_snapshots=[
                PanelSnapshot(
                    dashboard_uid="abc",
                    panel_id=1,
                    query="rate(cpu[5m])",
                    image_path="/tmp/panel_abc_1.png",
                    caption="CPU使用率推移",
                ),
            ],
        )
        md = render_rca_markdown(report)

        assert "`rate(cpu[5m])`" in md
        assert "![CPU使用率推移](/tmp/panel_abc_1.png)" in md

    def test_render_with_log_excerpts(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
            log_excerpts=[
                LogExcerpt(
                    query='{job="myapp"}',
                    entries=[
                        LogEntry(
                            timestamp=datetime(2026, 2, 1, 16, 5, 0, tzinfo=UTC),
                            level="error",
                            message="OutOfMemoryError",
                        ),
                    ],
                    caption="OOMログ",
                ),
            ],
        )
        md = render_rca_markdown(report)

        assert "### OOMログ" in md
        assert '`{job="myapp"}`' in md
        assert "[error] OutOfMemoryError" in md
        assert "```" in md

    def test_render_footer(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
        )
        md = render_rca_markdown(report)
        assert "Generated by AI Agent Monitoring System" in md
