"""core/renderer のテスト."""

from datetime import UTC, datetime

from ai_agent_monitoring.core.models import (
    LogEntry,
    LogExcerpt,
    PanelSnapshot,
    RCAReport,
    RootCause,
    TriggerType,
)
from ai_agent_monitoring.core.renderer import _format_summary_text, render_rca_markdown


class TestRenderRCAMarkdown:
    def test_render_with_alert(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
            root_causes=[
                RootCause(
                    description="メモリリーク",
                    confidence=0.9,
                    evidence=["MemAvailable が 100MB以下"],
                ),
            ],
            metrics_summary="CPU使用率が95%超過",
            logs_summary="OOMエラーが発生",
            recommendations=["メモリ上限を引き上げる"],
        )
        md = render_rca_markdown(report)

        assert "# RCA レポート" in md
        assert "HighCPUUsage" in md
        assert "critical" in md
        assert "メモリリーク" in md
        assert "90%" in md
        assert "█████████░" in md  # confidence bar
        assert "メモリ上限を引き上げる" in md

    def test_render_with_user_query(self, sample_user_query):
        report = RCAReport(
            trigger_type=TriggerType.USER_QUERY,
            user_query=sample_user_query,
            root_causes=[],
        )
        md = render_rca_markdown(report)

        assert "ユーザ問い合わせ" in md
        assert "昨日の16時ごろ" in md
        assert "根本原因を特定できませんでした" in md

    def test_render_with_panel_snapshots(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
            panel_snapshots=[
                PanelSnapshot(
                    dashboard_uid="abc",
                    panel_id=1,
                    query="rate(cpu[5m])",
                    image_path="/tmp/panel_abc_1.png",
                    caption="CPU使用率推移",
                ),
            ],
        )
        md = render_rca_markdown(report)

        assert "`rate(cpu[5m])`" in md
        assert "![CPU使用率推移](/tmp/panel_abc_1.png)" in md

    def test_render_with_log_excerpts(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
            log_excerpts=[
                LogExcerpt(
                    query='{job="myapp"}',
                    entries=[
                        LogEntry(
                            timestamp=datetime(2026, 2, 1, 16, 5, 0, tzinfo=UTC),
                            level="error",
                            message="OutOfMemoryError",
                        ),
                    ],
                    caption="OOMログ",
                ),
            ],
        )
        md = render_rca_markdown(report)

        assert "### OOMログ" in md
        assert '`{job="myapp"}`' in md
        assert "[error] OutOfMemoryError" in md
        assert "```" in md

    def test_render_with_k8s_summary(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
            k8s_summary="Pod web-server-01 が OOMKilled により CrashLoopBackOff 状態。",
        )
        md = render_rca_markdown(report)

        assert "## Kubernetes分析" in md
        assert "OOMKilled" in md
        assert "CrashLoopBackOff" in md

    def test_render_without_k8s_summary(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
        )
        md = render_rca_markdown(report)
        assert "## Kubernetes分析" not in md

    def test_render_footer(self, sample_alert):
        report = RCAReport(
            trigger_type=TriggerType.ALERT,
            alert=sample_alert,
        )
        md = render_rca_markdown(report)
        assert "Generated by AI Agent Monitoring System" in md


class TestFormatSummaryText:
    def test_promql_function_wrapped_in_code_block(self):
        text = 'CPU使用率が高い:\nrate(node_cpu_seconds_total{mode="idle"}[5m])\n最大値 95%'
        result = _format_summary_text(text)

        assert "```promql" in result
        assert "rate(node_cpu_seconds_total" in result
        assert "```\n" in result

    def test_logql_selector_wrapped_in_code_block(self):
        text = 'エラーログ確認:\n{job="myapp", namespace="default"} |= "error"\nエラーパターン検出'
        result = _format_summary_text(text)

        assert "```logql" in result
        assert '{job="myapp"' in result

    def test_preserves_existing_code_block(self):
        text = "分析結果:\n```promql\nrate(cpu[5m])\n```\n以上"
        result = _format_summary_text(text)

        # 既にコードブロックがあるのでそのまま返す
        assert result == text

    def test_plain_text_unchanged(self):
        text = "CPU使用率が95%を超えました。メモリ使用量も高い状態です。"
        result = _format_summary_text(text)

        assert result == text

    def test_empty_text(self):
        assert _format_summary_text("") == ""

    def test_multiple_promql_queries(self):
        text = (
            "以下のクエリで確認:\n"
            'rate(http_requests_total{status="500"}[5m])\n'
            "異常検出:\n"
            'sum(increase(http_requests_total{status=~"5.."}[1h])) by (service)'
        )
        result = _format_summary_text(text)

        assert result.count("```promql") == 2

    def test_node_exporter_metric(self):
        text = 'メモリ確認:\nnode_memory_MemAvailable_bytes{instance="server-01"}\n残り100MB'
        result = _format_summary_text(text)

        assert "```promql" in result
        assert "node_memory_MemAvailable_bytes" in result
