"""RCAレポートの Markdown レンダラー."""

from ai_agent_monitoring.core.models import RCAReport


def render_rca_markdown(report: RCAReport) -> str:
    """RCAReportをMarkdown形式にレンダリング."""
    lines: list[str] = []

    # ヘッダー
    lines.append("# RCA レポート")
    lines.append("")
    lines.append(f"**生成日時:** {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("")

    # トリガー情報
    lines.append("## トリガー")
    lines.append("")
    if report.alert:
        lines.append("| 項目 | 内容 |")
        lines.append("|------|------|")
        lines.append("| **種別** | アラート |")
        lines.append(f"| **名前** | {report.alert.alert_name} |")
        lines.append(f"| **重要度** | {report.alert.severity} |")
        lines.append(f"| **インスタンス** | {report.alert.instance} |")
        lines.append(f"| **概要** | {report.alert.summary} |")
        lines.append(f"| **発生時刻** | {report.alert.starts_at.strftime('%Y-%m-%d %H:%M:%S')} |")
    elif report.user_query:
        lines.append("| 項目 | 内容 |")
        lines.append("|------|------|")
        lines.append("| **種別** | ユーザ問い合わせ |")
        lines.append(f"| **内容** | {report.user_query.raw_input} |")
    lines.append("")

    # 根本原因
    lines.append("## 根本原因分析")
    lines.append("")
    if report.root_causes:
        for i, rc in enumerate(report.root_causes, 1):
            confidence_bar = _confidence_bar(rc.confidence)
            lines.append(f"### 原因 {i}: {rc.description}")
            lines.append("")
            lines.append(f"**信頼度:** {rc.confidence:.0%} {confidence_bar}")
            lines.append("")
            if rc.evidence:
                lines.append("**エビデンス:**")
                lines.append("")
                for ev in rc.evidence:
                    lines.append(f"- {ev}")
                lines.append("")
    else:
        lines.append("根本原因を特定できませんでした。")
        lines.append("")

    # メトリクス分析
    lines.append("## メトリクス分析")
    lines.append("")
    if report.metrics_summary:
        lines.append(report.metrics_summary)
        lines.append("")

    # グラフ画像
    if report.panel_snapshots:
        for snap in report.panel_snapshots:
            if snap.query:
                lines.append(f"**クエリ:** `{snap.query}`")
                lines.append("")
            if snap.image_path:
                caption = snap.caption or f"Panel {snap.panel_id}"
                lines.append(f"![{caption}]({snap.image_path})")
                lines.append("")

    # ログ分析
    lines.append("## ログ分析")
    lines.append("")
    if report.logs_summary:
        lines.append(report.logs_summary)
        lines.append("")

    # ログ抜粋
    if report.log_excerpts:
        for excerpt in report.log_excerpts:
            if excerpt.caption:
                lines.append(f"### {excerpt.caption}")
                lines.append("")
            if excerpt.query:
                lines.append(f"**クエリ:** `{excerpt.query}`")
                lines.append("")
            if excerpt.entries:
                lines.append("```")
                for entry in excerpt.entries:
                    ts = entry.timestamp.strftime("%Y-%m-%d %H:%M:%S")
                    lines.append(f"[{ts}] [{entry.level}] {entry.message}")
                lines.append("```")
                lines.append("")

    # 推奨アクション
    if report.recommendations:
        lines.append("## 推奨アクション")
        lines.append("")
        for rec in report.recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    # フッター
    lines.append("---")
    lines.append("*Generated by AI Agent Monitoring System*")

    return "\n".join(lines)


def _confidence_bar(confidence: float) -> str:
    """信頼度をプログレスバーで表現."""
    filled = round(confidence * 10)
    return "█" * filled + "░" * (10 - filled)
